(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const o of t.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&i(o)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();const c=document.querySelector(".backdrop"),m=document.querySelector(".burger-menu-wrap"),y=document.querySelector(".menu-close-btn"),a=document.querySelector(".backdrop-overlay"),k=document.querySelectorAll(".mob-menu-item a"),f=()=>{c.classList.add("is-open"),a.classList.add("is-open"),c.style.visibility="visible",a.style.visibility="visible"},p=()=>{c.classList.remove("is-open"),a.classList.remove("is-open"),setTimeout(()=>{c.style.visibility="hidden",a.style.visibility="hidden"},300)};k.forEach(l=>{l.addEventListener("click",r=>{p()})});m.addEventListener("click",f);y.addEventListener("click",p);window.calculatePlan=function(){const r=[{name:"STERYL 20",packets:20,price:110},{name:"STERYL 30",packets:30,price:140},{name:"STERYL 50",packets:50,price:210},{name:"STERYL 100",packets:100,price:300},{name:"STERYL 150",packets:150,price:360},{name:"STERYL 200",packets:200,price:430},{name:"STERYL 300",packets:300,price:550},{name:"STERYL 500",packets:500,price:780}],s=parseInt(document.querySelector("#packets").value),i=document.querySelector("#result");if(isNaN(s)||s<=0){i.innerHTML="Proszę wpisać poprawną liczbę pakietów.";return}let e=null,t=1/0;r.forEach(o=>{const u=o.price/o.packets;let n=o.price;if(s>o.packets){const d=s-o.packets;n+=d*u}n<t&&(t=n,e={...o,totalCost:n,extraPackets:s>o.packets?s-o.packets:0,costPerPacket:u.toFixed(2)})}),e?i.innerHTML=`
      Przy ${s} pakietach miesięcznie najlepszym wyborem dla Ciebie jest abinament
      <strong>${e.name}</strong>.<br>
      Koszt sterylizacji jednego pakietu w tym abonamencie wynosi <strong>${e.costPerPacket} zł</strong>.<br>
      ${e.extraPackets>0?`Miesięczny koszt tego abonamentu to <strong>${e.price.toFixed(2)} zł </strong>, <br>
			   koszt sterylizacji ${e.extraPackets} pakietów poza abonamentem wynosi <strong>${e.extraPackets*e.costPerPacket} zł.</strong>`:"Brak dodatkowych kosztów. <br>"}
					<br> Całkowity koszt sterylizacli ${s} pakietów miesiecznie z abonamentem <strong>${e.name}</strong> wynosi <strong>${e.totalCost.toFixed(2)} zł. </strong>
					`:i.innerHTML="Nie znaleziono odpowiedniego abonamentu."};
//# sourceMappingURL=index.js.map
