(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const e of t)if(e.type==="childList")for(const c of e.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&n(c)}).observe(document,{childList:!0,subtree:!0});function o(t){const e={};return t.integrity&&(e.integrity=t.integrity),t.referrerPolicy&&(e.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?e.credentials="include":t.crossOrigin==="anonymous"?e.credentials="omit":e.credentials="same-origin",e}function n(t){if(t.ep)return;t.ep=!0;const e=o(t);fetch(t.href,e)}})();const a=document.querySelector(".backdrop"),y=document.querySelector(".burger-menu-wrap"),k=document.querySelector(".menu-close-btn"),l=document.querySelector(".backdrop-overlay"),f=document.querySelectorAll(".mob-menu-item a"),b=()=>{a.classList.add("is-open"),l.classList.add("is-open"),a.style.visibility="visible",l.style.visibility="visible"},p=()=>{a.classList.remove("is-open"),l.classList.remove("is-open"),setTimeout(()=>{a.style.visibility="hidden",l.style.visibility="hidden"},300)};f.forEach(u=>{u.addEventListener("click",r=>{p()})});y.addEventListener("click",b);k.addEventListener("click",p);window.calculatePlan=function(){const r=[{name:"STERYL 20",packets:20,price:110},{name:"STERYL 30",packets:30,price:140},{name:"STERYL 50",packets:50,price:210},{name:"STERYL 100",packets:100,price:300},{name:"STERYL 150",packets:150,price:360},{name:"STERYL 200",packets:200,price:430},{name:"STERYL 300",packets:300,price:550},{name:"STERYL 500",packets:500,price:780}],o=parseInt(document.querySelector("#packets").value),n=document.querySelector("#result"),t=document.querySelector(".calc-button");if(isNaN(o)||o<=0){n.innerHTML="Proszę wpisać poprawną liczbę pakietów.";return}let e=null,c=1/0;r.forEach(s=>{const d=s.price/s.packets;let i=s.price;if(o>s.packets){const m=o-s.packets;i+=m*d}i<c&&(c=i,e={...s,totalCost:i,extraPackets:o>s.packets?o-s.packets:0,costPerPacket:d.toFixed(2)})}),e?n.innerHTML=`
      Przy ${o} pakietach miesięcznie najlepszym wyborem dla Ciebie jest abonament
      <strong>${e.name}</strong>.<br>
      Koszt sterylizacji jednego pakietu w tym abonamencie wynosi <strong>${e.costPerPacket} zł</strong>.<br>
      ${e.extraPackets>0?`Miesięczny koszt tego abonamentu to <strong>${e.price.toFixed(2)} zł </strong>, <br>
			   koszt sterylizacji ${e.extraPackets} pakietów poza abonamentem wynosi <strong>${e.extraPackets*e.costPerPacket} zł.</strong>`:"Brak dodatkowych kosztów. <br>"}
					<br> Całkowity koszt sterylizacli ${o} pakietów miesiecznie z abonamentem <strong>${e.name}</strong> wynosi <strong>${e.totalCost.toFixed(2)} zł. </strong>
					`:n.innerHTML="Nie znaleziono odpowiedniego abonamentu.",t.blur()};
//# sourceMappingURL=index.js.map
